Repository ThiagoLopezA/Skill-Up-JS-Backend-02, pull requests merged in 2022-12, with the labels that each got.

#5 Categories seeders
  database/seeders/20221201231501-refill-categories.js
Labels: enhancement

#7 Endpoint users authentication
  controllers/auth.js
  database/migrations/20220928193519-create-user.js
  database/migrations/20221201104223-create-transaction.js
  database/models/user.js
  helpers/bcrypt.helper.js
  package-lock.json
  package.json
  routes/auth.js
  routes/index.js
  services/user.service.js
Labels: enhancement

#14 <fix>[helpers]: ErrorObject require fixed
  helpers/jwt.helper.js
Labels: bug

#12 Show all categories route added
  controllers/categories.js
  package-lock.json
  routes/categories.js
  services/categories.service.js
Labels: enhancement

#21 <feat>[seeders]: Users seeders
  .gitignore
  controllers/transactions.js
  database/seeders/20221204000815-create-users.js
  routes/index.js
  routes/transactions.js
  services/transactions.service.js
  utils/user.png
Labels: enhancement

#28 <fix>[seeders]Users with the correct role and update readme with users
  README.md
  database/seeders/20221204000815-create-users.js
Labels: fix

#33 <feat>[test]: Testing users
  config/config.js
  database/seeders/test/20221209140219-test-users.js
  package-lock.json
  package.json
  test/user.test.js
Labels: enhancement

#38 <fix>[test]:authentication in user test
  routes/auth.js
  routes/users.js
  schemas/user.js
  services/users.service.js
  test/user.test.js
Labels: fix

#46 Card 33
  controllers/users.js
  database/seeders/20221204000815-create-users.js
  helpers/validateAuth.js
  middlewares/authentication.js
  middlewares/ownership.js
  middlewares/uploads.js
  middlewares/validateTokenTransaction.js
  package-lock.json
  package.json
  public/uploads/1670985351564.webp
  public/uploads/1670985373065.webp
  routes/auth.js
  routes/transactions.js
  routes/users.js
Labels: enhancement
